version: '3.7'
services:
  remoteSensingCustomContainer:
    container_name: mdSetup
    image: ghcr.io/kai-tub/ip4rs-dependencies:latest
    volumes:
          - ./:/work
    ports:
      - "8888:8888"
    working_dir: /work